
use_frameworks!

platform :ios, '10.0'

target 'PoliSDK_Example' do
  pod 'PoliSDK', :path => '../'

  target 'PoliSDK_Tests' do
    inherit! :search_paths

    pod 'Nimble', '~> 10.0.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
