source 'https://github.com/hconnectdx/ios-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'PoliSDK_Example' do
  pod 'PoliSDK', :path => '../'
  pod 'HCBle', '~> 0.1.3'
end
